### PR TITLE
fix in preparation for https://github.com/nim-lang/Nim/pull/14447

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @araq fix in preparation for https://github.com/nim-lang/Nim/pull/14447

@Vindaar CI is failing here but looks like master is already failing

### CODE REVIEW

**Comment by Vindaar** [comment]
Oh, I didn't realize master was still failing. Weird. I was sure I checked travis back after I did those commits. I wasn't around for the last couple of weeks. I'll check your Nim PR later.

I didn't use `capture` in the code iirc, because it was only available from Nim 1.2? But maybe I misremember.

**Comment by Vindaar** [comment]
> Oh, I didn't realize master was still failing. Weird. I was sure I checked travis back after I did those commits. I wasn't around for the last couple of weeks. I'll check your Nim PR later.

It did indeed pass before. The thing I didn't catch was that the recipe to highlight date time usage includes a call to `now` which causes the CI to fail after a month with that recipe.

**Comment by timotheecour** [comment]
I had ended up adding -d:nimWorkaround14447 in https://github.com/nim-lang/Nim/pull/14447/files#diff-4dede0b24c7aa57b7d2fdf293ccf6569R46 to unblock that PR

but with this PR, -d:nimWorkaround14447 would not be needed and can/should be removed from https://github.com/nim-lang/Nim/pull/14447/files#diff-4dede0b24c7aa57b7d2fdf293ccf6569R46

**Comment by Vindaar** [comment]
Sorry for taking so long for this.

Thanks for the PR!

**Pull request merged**
