### PR TITLE
fix deprecated stuff

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

**Comment by Vindaar** [comment]
Haha, thanks a bunch. I was aware of those, especially after I saw your other PRs. Thanks for taking your time on this. :)

**Comment by narimiran** [comment]
> I was aware of those

I'm trying to clean-up stdlib of these long-deprecated stuff, so in my branch it is much easier to spot all those deprecations — they don't compile anymore :D

**Comment by Vindaar** [comment]
> I'm trying to clean-up stdlib of these long-deprecated stuff, so in my branch it is much easier to spot all those deprecations — they don't compile anymore :D

Oh, that's good. So we'll get rid of some deprecated procs soon? :)

**Comment by narimiran** [comment]
> So we'll get rid of some deprecated procs soon?

That's my plan, but who knows what "soon" really means.... :D

**Pull request merged**
